name: Test puppeter with ubuntu

on:
  push:
#  workflow_dispatch:

jobs:
  automation:
#    runs-on: ubuntu-20.04
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.3.0'

      - run: npm ci
#      - run: node jsdom.js
      - run: npm run s
